name: Cypress CI (Robust)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cypress:
    name: e2e-${{ matrix.browser }}-shard-${{ matrix.shard }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - browser: chrome
            shard: 1
          - browser: chrome
            shard: 2
          - browser: chrome
            shard: 3
          - browser: firefox
            shard: 1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          headed: false
          # run only the two demo specs
          spec: cypress/e2e/framework-demo.cy.js,cypress/e2e/api-tests.cy.js
        env:
          CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports-${{ matrix.browser }}-${{ matrix.shard }}
          path: cypress/reports
          if-no-files-found: warn

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.browser }}-${{ matrix.shard }}
          path: cypress/screenshots
          if-no-files-found: warn

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.browser }}-${{ matrix.shard }}
          path: cypress/videos
          if-no-files-found: warn

  report:
    name: merge-and-publish-report
    runs-on: ubuntu-latest
    needs: cypress
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Merge mochawesome JSON
        run: |
          ls -R artifacts || true
          npx mochawesome-merge "artifacts/**/mochawesome*.json" > merged-report.json || echo "No reports to merge"
      
      - name: Generate HTML report
        run: |
          if [ -f "merged-report.json" ]; then
            npx marge merged-report.json --reportDir final-report --inline
          else
            echo "No merged-report.json found, skipping HTML generation"
          fi

      - name: Upload final report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: final-report
          path: final-report
          if-no-files-found: warn
